/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BackupRouteImport } from './routes/backup'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ContasRouteImport } from './routes/contas'
import { Route as FormasRouteImport } from './routes/formas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MateriaisRouteImport } from './routes/materiais'
import { Route as PecasRouteImport } from './routes/pecas'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as PrecificacaoRouteImport } from './routes/precificacao'
import { Route as TransacoesRouteImport } from './routes/transacoes'
import { Route as ClientesClienteIdRouteImport } from './routes/clientes.$clienteId'
import { Route as PecasPecaIdRouteImport } from './routes/pecas.$pecaId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupRoute = BackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContasRoute = ContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => rootRouteImport,
} as any)
const FormasRoute = FormasRouteImport.update({
  id: '/formas',
  path: '/formas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriaisRoute = MateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => rootRouteImport,
} as any)
const PecasRoute = PecasRouteImport.update({
  id: '/pecas',
  path: '/pecas',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecificacaoRoute = PrecificacaoRouteImport.update({
  id: '/precificacao',
  path: '/precificacao',
  getParentRoute: () => rootRouteImport,
} as any)
const TransacoesRoute = TransacoesRouteImport.update({
  id: '/transacoes',
  path: '/transacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesClienteIdRoute = ClientesClienteIdRouteImport.update({
  id: '/$clienteId',
  path: '/$clienteId',
  getParentRoute: () => ClientesRoute,
} as any)
const PecasPecaIdRoute = PecasPecaIdRouteImport.update({
  id: '/$pecaId',
  path: '/$pecaId',
  getParentRoute: () => PecasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backup': typeof BackupRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas': typeof ContasRoute
  '/formas': typeof FormasRoute
  '/login': typeof LoginRoute
  '/materiais': typeof MateriaisRoute
  '/pecas': typeof PecasRouteWithChildren
  '/pedidos': typeof PedidosRoute
  '/precificacao': typeof PrecificacaoRoute
  '/transacoes': typeof TransacoesRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRoute
  '/pecas/$pecaId': typeof PecasPecaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backup': typeof BackupRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas': typeof ContasRoute
  '/formas': typeof FormasRoute
  '/login': typeof LoginRoute
  '/materiais': typeof MateriaisRoute
  '/pecas': typeof PecasRouteWithChildren
  '/pedidos': typeof PedidosRoute
  '/precificacao': typeof PrecificacaoRoute
  '/transacoes': typeof TransacoesRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRoute
  '/pecas/$pecaId': typeof PecasPecaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backup': typeof BackupRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas': typeof ContasRoute
  '/formas': typeof FormasRoute
  '/login': typeof LoginRoute
  '/materiais': typeof MateriaisRoute
  '/pecas': typeof PecasRouteWithChildren
  '/pedidos': typeof PedidosRoute
  '/precificacao': typeof PrecificacaoRoute
  '/transacoes': typeof TransacoesRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRoute
  '/pecas/$pecaId': typeof PecasPecaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backup'
    | '/clientes'
    | '/configuracoes'
    | '/contas'
    | '/formas'
    | '/login'
    | '/materiais'
    | '/pecas'
    | '/pedidos'
    | '/precificacao'
    | '/transacoes'
    | '/clientes/$clienteId'
    | '/pecas/$pecaId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backup'
    | '/clientes'
    | '/configuracoes'
    | '/contas'
    | '/formas'
    | '/login'
    | '/materiais'
    | '/pecas'
    | '/pedidos'
    | '/precificacao'
    | '/transacoes'
    | '/clientes/$clienteId'
    | '/pecas/$pecaId'
  id:
    | '__root__'
    | '/'
    | '/backup'
    | '/clientes'
    | '/configuracoes'
    | '/contas'
    | '/formas'
    | '/login'
    | '/materiais'
    | '/pecas'
    | '/pedidos'
    | '/precificacao'
    | '/transacoes'
    | '/clientes/$clienteId'
    | '/pecas/$pecaId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackupRoute: typeof BackupRoute
  ClientesRoute: typeof ClientesRouteWithChildren
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContasRoute: typeof ContasRoute
  FormasRoute: typeof FormasRoute
  LoginRoute: typeof LoginRoute
  MateriaisRoute: typeof MateriaisRoute
  PecasRoute: typeof PecasRouteWithChildren
  PedidosRoute: typeof PedidosRoute
  PrecificacaoRoute: typeof PrecificacaoRoute
  TransacoesRoute: typeof TransacoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup': {
      id: '/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof BackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contas': {
      id: '/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof ContasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formas': {
      id: '/formas'
      path: '/formas'
      fullPath: '/formas'
      preLoaderRoute: typeof FormasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiais': {
      id: '/materiais'
      path: '/materiais'
      fullPath: '/materiais'
      preLoaderRoute: typeof MateriaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pecas': {
      id: '/pecas'
      path: '/pecas'
      fullPath: '/pecas'
      preLoaderRoute: typeof PecasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precificacao': {
      id: '/precificacao'
      path: '/precificacao'
      fullPath: '/precificacao'
      preLoaderRoute: typeof PrecificacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transacoes': {
      id: '/transacoes'
      path: '/transacoes'
      fullPath: '/transacoes'
      preLoaderRoute: typeof TransacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$clienteId': {
      id: '/clientes/$clienteId'
      path: '/$clienteId'
      fullPath: '/clientes/$clienteId'
      preLoaderRoute: typeof ClientesClienteIdRouteImport
      parentRoute: typeof ClientesRoute
    }
    '/pecas/$pecaId': {
      id: '/pecas/$pecaId'
      path: '/$pecaId'
      fullPath: '/pecas/$pecaId'
      preLoaderRoute: typeof PecasPecaIdRouteImport
      parentRoute: typeof PecasRoute
    }
  }
}

interface ClientesRouteChildren {
  ClientesClienteIdRoute: typeof ClientesClienteIdRoute
}

const ClientesRouteChildren: ClientesRouteChildren = {
  ClientesClienteIdRoute: ClientesClienteIdRoute,
}

const ClientesRouteWithChildren = ClientesRoute._addFileChildren(
  ClientesRouteChildren,
)

interface PecasRouteChildren {
  PecasPecaIdRoute: typeof PecasPecaIdRoute
}

const PecasRouteChildren: PecasRouteChildren = {
  PecasPecaIdRoute: PecasPecaIdRoute,
}

const PecasRouteWithChildren = PecasRoute._addFileChildren(PecasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackupRoute: BackupRoute,
  ClientesRoute: ClientesRouteWithChildren,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ContasRoute: ContasRoute,
  FormasRoute: FormasRoute,
  LoginRoute: LoginRoute,
  MateriaisRoute: MateriaisRoute,
  PecasRoute: PecasRouteWithChildren,
  PedidosRoute: PedidosRoute,
  PrecificacaoRoute: PrecificacaoRoute,
  TransacoesRoute: TransacoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
