/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormasRouteImport } from './routes/formas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MateriaisRouteImport } from './routes/materiais'
import { Route as PecasRouteImport } from './routes/pecas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormasRoute = FormasRouteImport.update({
  id: '/formas',
  path: '/formas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriaisRoute = MateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => rootRouteImport,
} as any)
const PecasRoute = PecasRouteImport.update({
  id: '/pecas',
  path: '/pecas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/formas': typeof FormasRoute
  '/login': typeof LoginRoute
  '/materiais': typeof MateriaisRoute
  '/pecas': typeof PecasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/formas': typeof FormasRoute
  '/login': typeof LoginRoute
  '/materiais': typeof MateriaisRoute
  '/pecas': typeof PecasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/formas': typeof FormasRoute
  '/login': typeof LoginRoute
  '/materiais': typeof MateriaisRoute
  '/pecas': typeof PecasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/formas' | '/login' | '/materiais' | '/pecas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/formas' | '/login' | '/materiais' | '/pecas'
  id: '__root__' | '/' | '/formas' | '/login' | '/materiais' | '/pecas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormasRoute: typeof FormasRoute
  LoginRoute: typeof LoginRoute
  MateriaisRoute: typeof MateriaisRoute
  PecasRoute: typeof PecasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formas': {
      id: '/formas'
      path: '/formas'
      fullPath: '/formas'
      preLoaderRoute: typeof FormasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiais': {
      id: '/materiais'
      path: '/materiais'
      fullPath: '/materiais'
      preLoaderRoute: typeof MateriaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pecas': {
      id: '/pecas'
      path: '/pecas'
      fullPath: '/pecas'
      preLoaderRoute: typeof PecasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormasRoute: FormasRoute,
  LoginRoute: LoginRoute,
  MateriaisRoute: MateriaisRoute,
  PecasRoute: PecasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
