-- Migration: 20260929174500_add_perfil_id.sql
-- Add multi-profile support (up to 10 profiles per user)

-- 1. Create perfis table
CREATE TABLE perfis (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  criado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE perfis ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users manage seus perfis" ON perfis FOR ALL USING (auth.uid() = user_id);

-- 2. Add perfil_id to all tables
ALTER TABLE contas ADD COLUMN perfil_id BIGINT REFERENCES perfis(id) ON DELETE CASCADE;
ALTER TABLE categorias_material ADD COLUMN perfil_id BIGINT REFERENCES perfis(id) ON DELETE CASCADE;
ALTER TABLE materiais ADD COLUMN perfil_id BIGINT REFERENCES perfis(id) ON DELETE CASCADE;
ALTER TABLE formas ADD COLUMN perfil_id BIGINT REFERENCES perfis(id) ON DELETE CASCADE;
ALTER TABLE equipamentos ADD COLUMN perfil_id BIGINT REFERENCES perfis(id) ON DELETE CASCADE;
ALTER TABLE pecas ADD COLUMN perfil_id BIGINT REFERENCES perfis(id) ON DELETE CASCADE;
ALTER TABLE consumos_peca ADD COLUMN perfil_id BIGINT REFERENCES perfis(id) ON DELETE CASCADE;
ALTER TABLE clientes ADD COLUMN perfil_id BIGINT REFERENCES perfis(id) ON DELETE CASCADE;
ALTER TABLE pedidos ADD COLUMN perfil_id BIGINT REFERENCES perfis(id) ON DELETE CASCADE;
ALTER TABLE transacoes ADD COLUMN perfil_id BIGINT REFERENCES perfis(id) ON DELETE CASCADE;
ALTER TABLE configuracoes ADD COLUMN perfil_id BIGINT REFERENCES perfis(id) ON DELETE CASCADE;
ALTER TABLE taxas ADD COLUMN perfil_id BIGINT REFERENCES perfis(id) ON DELETE CASCADE;

-- Note: We are keeping auth.uid() = user_id as the primary RLS barrier for security.
-- The application logic will enforce the isolation of data by perfil_id.
