-- Migration: 20260929171103_init_schema.sql
-- Create initial tables with RLS and user_id isolation

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Contas
CREATE TABLE contas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  saldo_criptografado TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE contas ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users manage their own contas" ON contas FOR ALL USING (auth.uid() = user_id);

-- 2. Categorias Material
CREATE TABLE categorias_material (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  categoria_pai_id BIGINT,
  tipo_classificacao TEXT
);
ALTER TABLE categorias_material ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users manage their own categorias" ON categorias_material FOR ALL USING (auth.uid() = user_id);

-- 3. Materiais
CREATE TABLE materiais (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  categoria_id BIGINT NOT NULL,
  subcategoria_id BIGINT,
  unidade TEXT NOT NULL,
  quantidade_estoque REAL NOT NULL DEFAULT 0,
  custo_unitario REAL NOT NULL DEFAULT 0,
  valor_frete REAL,
  tipo_classificacao TEXT
);
ALTER TABLE materiais ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users manage their own materiais" ON materiais FOR ALL USING (auth.uid() = user_id);

-- 4. Formas
CREATE TABLE formas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  geometria TEXT NOT NULL,
  dimensoes_cm JSONB,
  volume_direto_ml REAL,
  custo_fabricacao REAL,
  custo_caixa_estrutura REAL,
  material_caixa_estrutura TEXT,
  vida_util_usos INTEGER,
  usos_realizados INTEGER,
  material_silicone_id BIGINT,
  quantidade_silicone_usada REAL,
  cura_iniciada_em BIGINT,
  cura_minutos INTEGER,
  status TEXT,
  cavidades JSONB,
  furos_vazados JSONB,
  pes_mesa JSONB,
  margem_seguranca_percentual REAL,
  massa_resina_kg REAL,
  litros_resina REAL,
  imagem_url TEXT
);
ALTER TABLE formas ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users manage their own formas" ON formas FOR ALL USING (auth.uid() = user_id);

-- 5. Equipamentos
CREATE TABLE equipamentos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  potencia_watts REAL NOT NULL,
  valor_compra REAL,
  descricao TEXT,
  vida_util_horas REAL,
  criado_em TEXT
);
ALTER TABLE equipamentos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users manage their own equipamentos" ON equipamentos FOR ALL USING (auth.uid() = user_id);

-- 6. Pecas
CREATE TABLE pecas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  numero_serie TEXT,
  nome TEXT NOT NULL,
  forma_id BIGINT NOT NULL,
  status TEXT NOT NULL,
  criada_em TEXT NOT NULL,
  preco_venda REAL,
  cura_iniciada_em BIGINT,
  cura_minutos INTEGER,
  tipo_processo TEXT,
  duracao_processo_minutos INTEGER,
  horas_mao_de_obra REAL,
  mao_de_obra_fixa REAL,
  usos_energia JSONB,
  percentual_taxas REAL,
  margem_desejada REAL,
  imagem_url TEXT,
  volume_resina_ml REAL,
  litros_agua REAL,
  custo_agua REAL,
  custo_epi_insumos REAL,
  valor_propaganda_total REAL,
  dias_propaganda INTEGER,
  custo_propaganda_calculado REAL,
  valor_frete REAL
);
ALTER TABLE pecas ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users manage their own pecas" ON pecas FOR ALL USING (auth.uid() = user_id);

-- 7. Consumos Peca
CREATE TABLE consumos_peca (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  peca_id BIGINT NOT NULL,
  material_id BIGINT NOT NULL,
  quantidade REAL NOT NULL,
  unidade TEXT
);
ALTER TABLE consumos_peca ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users manage suas consumos" ON consumos_peca FOR ALL USING (auth.uid() = user_id);

-- 8. Clientes
CREATE TABLE clientes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  contato TEXT
);
ALTER TABLE clientes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users manage seus clientes" ON clientes FOR ALL USING (auth.uid() = user_id);

-- 9. Pedidos
CREATE TABLE pedidos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  cliente_id BIGINT NOT NULL,
  peca_ids JSONB NOT NULL,
  status TEXT NOT NULL,
  criado_em TEXT NOT NULL,
  prazo_entrega TEXT,
  etapa TEXT,
  progresso INTEGER
);
ALTER TABLE pedidos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users manage seus pedidos" ON pedidos FOR ALL USING (auth.uid() = user_id);

-- 10. Transacoes
CREATE TABLE transacoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  conta_id BIGINT NOT NULL,
  tipo TEXT NOT NULL,
  valor_criptografado TEXT NOT NULL,
  descricao TEXT NOT NULL,
  data TEXT NOT NULL
);
ALTER TABLE transacoes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users manage suas transacoes" ON transacoes FOR ALL USING (auth.uid() = user_id);

-- 11. Configuracoes
CREATE TABLE configuracoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  chave TEXT NOT NULL,
  valor TEXT NOT NULL
);
ALTER TABLE configuracoes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users manage config" ON configuracoes FOR ALL USING (auth.uid() = user_id);

-- 12. Taxas
CREATE TABLE taxas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  percentual REAL NOT NULL,
  valor_fixo REAL NOT NULL,
  criado_em TEXT NOT NULL
);
ALTER TABLE taxas ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users manage taxas" ON taxas FOR ALL USING (auth.uid() = user_id);
